<a href="https://colab.research.google.com/github/gagyeomkim/Deep-Learning-Paper-Review-and-Practice/blob/main/code_practice/Sequence_to_Sequence_with_GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Sequence to Sequence Learning with Neural Networks (NIPS 2014) 실습**

- 본 코드는 **Attention을 이용하지 않은 Seq2Seq**으로 간단한 한글 챗봇을 제작합니다.
    - 본 논문은 딥러닝 기반의 자연어 처리 기법의 기본적인 구성을 이해하고 공부하는 데에 도움을 줍니다.
    - 2020년 기준 가장 뛰어난 번역 모델은 Seq2Seq가 아닌 Transformer 기반의 모델입니다.
- 코드 실행 전에 **[런타임] → [런타임 유형 변경]** → 유형을 **GPU**로 설정합니다

ref: https://teddylee777.github.io/pytorch/pytorch-seq2seq-chatbot/

##### **데이터 다운로드**

In [ ]:
!pwd
!mkdir data

/content


- ref: https://me-coding.tistory.com/45

In [ ]:
!wget https://raw.githubusercontent.com/songys/Chatbot_data/refs/heads/master/ChatbotData.csv -O data/ChatbotData.csv

--2025-07-10 21:01:21--  https://raw.githubusercontent.com/songys/Chatbot_data/refs/heads/master/ChatbotData.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 889842 (869K) [text/plain]
Saving to: ‘data/ChatbotData.csv’

data/ChatbotData.cs 100%[===================>] 868.99K  --.-KB/s    in 0.005s  

2025-07-10 21:01:22 (157 MB/s) - ‘data/ChatbotData.csv’ saved [889842/889842]



- 형태소 분석기 다운로드

In [ ]:
!pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 112.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 496.6/496.6 kB 46.5 MB/s eta 0:00:00


In [ ]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git

Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 138 (delta 26), reused 22 (delta 8), pack-reused 91 (from 1)
Receiving objects: 100% (138/138), 1.72 MiB | 32.52 MiB/s, done.
Resolving deltas: 100% (65/65), done.


In [ ]:
cd Mecab-ko-for-Google-Colab

/content/Mecab-ko-for-Google-Colab


In [ ]:
!bash install_mecab-ko_on_colab_light_220429.sh

Installing konlpy.....
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2025-07-10 21:01:32--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 13.200.41.136, 13.200.41.134, 13.200.41.135, ...
Connecting to bitbucket.org (bitbucket.org)|13.200.41.136|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None&AWSAccessKeyId=ASIA6KOSE3BNI5OYCMDB&Signature=gg5tz5gss878xk0Fj%2FJY3DfU4yk%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEL3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJGMEQCIAVqPvSNaoYTfNOqh5Fa4ogibIy%2FEpQpPdD46aU9AQlEAiBNu%2BR0w4q38u3WhUtlv%2B1EYhrOUQuJ%2Fbt2Jab5I%2BslOCqwAgjG%2F%2F%2F%2F%2F%2F%2F%

- 원래 경로로 이동

In [ ]:
cd ../

/content


#### **모듈 import& 데이터로드**

In [ ]:
import os
import numpy as np
import pandas as pd
import random

data_dir = 'data'
print(f"경로: {os.path.join(data_dir, 'ChatbotData.csv')}")
df = pd.read_csv(os.path.join(data_dir, 'ChatbotData.csv'))
df

경로: data/ChatbotData.csv


Q                         A  label
0                       12시 땡!                하루가 또 가네요.      0
1                  1지망 학교 떨어졌어                 위로해 드립니다.      0
2                 3박4일 놀러가고 싶다               여행은 언제나 좋죠.      0
3              3박4일 정도 놀러가고 싶다               여행은 언제나 좋죠.      0
4                      PPL 심하네                눈살이 찌푸려지죠.      0
...                        ...                       ...    ...
11818           훔쳐보는 것도 눈치 보임.        티가 나니까 눈치가 보이는 거죠!      2
11819           훔쳐보는 것도 눈치 보임.             훔쳐보는 거 티나나봐요.      2
11820              흑기사 해주는 짝남.                    설렜겠어요.      2
11821  힘든 연애 좋은 연애라는게 무슨 차이일까?  잘 헤어질 수 있는 사이 여부인 거 같아요.      2
11822               힘들어서 결혼할까봐        도피성 결혼은 하지 않길 바라요.      2

[11823 rows x 3 columns]

In [ ]:
print(df['Q'])  # Series
question = df['Q']

print(df['A'])  # Series
answer = df['A']

0                         12시 땡!
1                    1지망 학교 떨어졌어
2                   3박4일 놀러가고 싶다
3                3박4일 정도 놀러가고 싶다
4                        PPL 심하네
                  ...           
11818             훔쳐보는 것도 눈치 보임.
11819             훔쳐보는 것도 눈치 보임.
11820                흑기사 해주는 짝남.
11821    힘든 연애 좋은 연애라는게 무슨 차이일까?
11822                 힘들어서 결혼할까봐
Name: Q, Length: 11823, dtype: object
0                      하루가 또 가네요.
1                       위로해 드립니다.
2                     여행은 언제나 좋죠.
3                     여행은 언제나 좋죠.
4                      눈살이 찌푸려지죠.
                   ...           
11818          티가 나니까 눈치가 보이는 거죠!
11819               훔쳐보는 거 티나나봐요.
11820                      설렜겠어요.
11821    잘 헤어질 수 있는 사이 여부인 거 같아요.
11822          도피성 결혼은 하지 않길 바라요.
Name: A, Length: 11823, dtype: object


> - Series란?: 인덱스와 일련의 값들로 구성된 인덱싱된 1차원 배열
    - https://digital-play.tistory.com/31

In [ ]:
question[:5]    # 상위 5개 출력

0             12시 땡!
1        1지망 학교 떨어졌어
2       3박4일 놀러가고 싶다
3    3박4일 정도 놀러가고 싶다
4            PPL 심하네
Name: Q, dtype: object

In [ ]:
answer[:5]  # 상위 5개 출력

0     하루가 또 가네요.
1      위로해 드립니다.
2    여행은 언제나 좋죠.
3    여행은 언제나 좋죠.
4     눈살이 찌푸려지죠.
Name: A, dtype: object

#### **데이터 전처리**

##### **한글 정규화**




In [ ]:
import re   # 정규표현식 모듈

# 한글, 영어, 숫자, 공백, ?!.,을 제외한 나머지 문자 제거
korean_pattern = r'[^ ?,.!A-Za-z0-9가-힣+]'  # + : 1번이상 반복되는 문자

# 패턴 컴파일
normalizer = re.compile(korean_pattern)
print(type(normalizer))
normalizer

<class 're.Pattern'>


re.compile(r'[^ ?,.!A-Za-z0-9가-힣+]', re.UNICODE)

> `re.compile`: 정규표현식을 컴파일하는 함수로, 패턴 객체가 만들어짐.   
-> 매번 패턴을 컴파일하는 과정을 생략할 수 있어 속도와 편의성면에서 유리함
- https://jh2021.tistory.com/7

In [ ]:
print(f"수정 전 : {question[10]}")
print(f"수정 후 : {normalizer.sub('',question[10])}")   # 패턴객체.sub(바꿀 문자열, 원본 문자열)
                                                      # 원본문자열에 있는 패턴을 "바꿀 문자열"로 변경

수정 전 : SNS보면 나만 빼고 다 행복해보여
수정 후 : SNS보면 나만 빼고 다 행복해보여


In [ ]:
print(f"수정 전 : {answer[10]}")
print(f"수정 후 : {normalizer.sub('',answer[10])}")

수정 전 : 자랑하는 자리니까요.
수정 후 : 자랑하는 자리니까요.


In [ ]:
# normalize 함수로 일반화
def normalize(sentence):
    return normalizer.sub("", sentence)

normalize(question[10])

'SNS보면 나만 빼고 다 행복해보여'

##### **한글 형태소 분석기**

- Mecab 설치방법
    - ref: https://github.com/SOMJANG/Mecab-ko-for-Google-Colab

In [ ]:
from konlpy.tag import Mecab, Okt   # 한국어 자연어 처리를 위한 패키지

# 형태소 분석기
mecab = Mecab()
okt = Okt()

- Konlpy에서는 형태소 분석기에 모두 동일한 메소드를 지원함
- `morphs()`: 형태소 추출
- `pos()`: 품사 태깅
- `nouns`: 명사 추출

In [ ]:
# mecab
mecab.morphs(normalize(question[10]))

['SNS', '보', '면', '나', '만', '빼', '고', '다', '행복', '해', '보여']

In [ ]:
# mecab
mecab.morphs(normalize(answer[10]))

['자랑', '하', '는', '자리', '니까요', '.']

In [ ]:
# okt
okt.morphs(normalize(question[10]))

['SNS', '보면', '나', '만', '빼고', '다', '행복', '해보여']

In [ ]:
okt.morphs(normalize(answer[10]))

['자랑', '하는', '자리', '니까', '요', '.']

ref: https://banmans.tistory.com/162  
성능 순위 : mecab > komoran > kkma > hannanum > okt  
속도 순위 : mecab >>> kkma > okt > hannanum > komoran

In [ ]:
# 한글 전처리를 함수화
def clean_text(sentence, tagger):
    sentence = normalize(sentence)  # 정규표현식 전처리
    # print(sentence)
    sentence = tagger.morphs(sentence)  # 형태소 추출
    # print(sentence)
    sentence = ' '.join(sentence)   # 추출한 형태소끼리 공백 1칸두고 합침
    # print(sentence)
    sentence = sentence.lower()  # 소문자 처리
    # print(sentence)
    return sentence

In [ ]:
clean_text(question[10], okt)

'sns 보면 나 만 빼고 다 행복 해보여'

In [ ]:
clean_text(answer[10], okt)

'자랑 하는 자리 니까 요 .'

In [ ]:
len(question), len(answer)

(11823, 11823)

In [ ]:
question = [clean_text(sent, okt) for sent in question[:1000]]   # 1000개의 question을 clean_text해서 리스트로 보관

answer = [clean_text(sent, okt) for sent in answer[:1000]]   # 1000개의 answer를 clean_text해서 리스트로 보관

In [ ]:
question[:5]

['12시 땡 !', '1 지망 학교 떨어졌어', '3 박 4일 놀러 가고 싶다', '3 박 4일 정도 놀러 가고 싶다', 'ppl 심하네']

In [ ]:
answer[:5]

['하루 가 또 가네요 .',
 '위로 해 드립니다 .',
 '여행 은 언제나 좋죠 .',
 '여행 은 언제나 좋죠 .',
 '눈살 이 찌푸려지죠 .']

##### **단어 사전 생성**

In [ ]:
import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
from torch.utils.data.dataset import Dataset

device = torch.device('cuda:0' if torch.cuda.is_available() else "cpu") # GPU 0번 사용
device

device(type='cuda', index=0)

In [ ]:
PAD_TOKEN = 0
SOS_TOKEN = 1
EOS_TOKEN = 2

class WordVocab():
    def __init__(self):
        # word->idx
        self.word2index = {
            "<PAD>": PAD_TOKEN, # 시퀀스의 길이를 맞추기 위한 패딩 토큰. 시퀀스들의 길이를 동일하게 맞춰주기 위해 추가되는 토큰
            "<SOS>": SOS_TOKEN, # 문장의 시작을 나타내는 토큰
            "<EOS>": EOS_TOKEN, # 문장의 끝을 나타내는 토큰
        }

        # 각 토큰별 word_count
        self.word2count = {}

        # idx->word
        self.index2word = {
            PAD_TOKEN: "<PAD>",
            SOS_TOKEN: "<SOS>",
            EOS_TOKEN: "<EOS>",
        }

        # total word counts
        self.n_words = 3    # <PAD>, <SOS>, <EOS> 포함 / # 새로운 단어는 index 3부터 시작

    def add_sentence(self, sentence):
        for word in sentence.split(' '):
            self.add_word(word)

    def add_word(self, word):
        if word not in self.word2index:
            self.word2index[word] = self.n_words    # n_words는 현재 단어 개수 = 새로 추가될 단어의 index
            self.word2count[word] = 1   # 새로운 단어의 count=1
            self.index2word[self.n_words] = word    # index2word에다가도 추가
            self.n_words += 1   # 현재 단어개수 = 새로추가될 단어의 index를 +1시킴
        else:
            self.word2count[word] += 1

In [ ]:
question[10]

'sns 보면 나 만 빼고 다 행복 해보여'

In [ ]:
print(f"원문: {question[10]}")
lang = WordVocab()
lang.add_sentence(question[10])
print('=='*10)
print('단어사전')
print(lang.word2index)

원문: sns 보면 나 만 빼고 다 행복 해보여
단어사전
{'<PAD>': 0, '<SOS>': 1, '<EOS>': 2, 'sns': 3, '보면': 4, '나': 5, '만': 6, '빼고': 7, '다': 8, '행복': 9, '해보여': 10}


##### **padding to sequences**
- 하나의 배치 구성을 위해서는 문장의 길이가 맞아야함
- 문장별로 길이가 다르기 때문에 길이를 맞춰주는 작업 수행
- 짧은 문장은 남는 공간에 `<PAD>` 토큰을 추가하여 길이를 맞춰줌

In [ ]:
max_length = 10
sentence_length = 6

sentence_tokens = np.random.randint(low=3, high=100, size=(sentence_length,))
# print(sentence_tokens)
sentence_tokens = sentence_tokens.tolist()  # array를 파이썬 list로 바꿔줌
print(f"Generated Sentence: {sentence_tokens}")

sentence_tokens = sentence_tokens[:(max_length-1)]  # (max_length-1) 미만까지 자름 - <EOS> 토큰도 들어가야해서 max_length가 아님
token_length = len(sentence_tokens)

# 문장의 맨 끝부분에 <EOS>토큰 추가
sentence_tokens.append(2)

for i in range(token_length, max_length-1):
    # 나머지 빈곳에 <PAD> 토큰 추가
    sentence_tokens.append(0)   # 꼭 <EOS>토큰이 맨 마지막에 들어가는게 아님. <EOS>는 "문장" 끝에 들어가는거지 패딩된거끝에 들어가는게 아님

print(f'Output: {sentence_tokens}')
print(f'Total Length: {len(sentence_tokens)}')

Generated Sentence: [63, 16, 21, 76, 62, 13]
Output: [63, 16, 21, 76, 62, 13, 2, 0, 0, 0]
Total Length: 10


###### **전처리 프로세스 클래스화**(위의 내용을 모아둔 것)
- torch.utils.data.Dataset을 상속받아 TextDataset 클래스를 구현
- 데이터를 로드하고, 정규화 및 전처리, 토큰화를 진행함
- 단어사전을 생성하고, 이에 따라 시퀀스로 변환

In [ ]:
from konlpy.tag import Mecab, Okt

class TextDataset(Dataset):
    def __init__(self, csv_path, min_length, max_length=32):
        super(TextDataset, self).__init__()
        data_dir = 'data'

        # TOKEN 정의
        self.PAD_TOKEN = 0  # Padding Token
        self.SOS_TOKEN = 1  # SOS 토큰
        self.EOS_TOKEN = 2  # EOS 토큰

        self.tagger = Mecab()   # 형태소 분석기
        self.max_length = max_length    # 한 문장의 최대 길이 지정

        # CSV 데이터 로드
        df = pd.read_csv(os.path.join(data_dir, csv_path))

        # 한글 정규화
        korean_pattern = r'[^ ?,.!A-Za-z0-9가-힣+]'
        self.normalizer = re.compile(korean_pattern)

        # src: 질의, tgt: 답변
        src_clean = []
        tgt_clean = []

        # 단어 사전 생성
        wordvocab = WordVocab()

        for _, row in df.iterrows():
            src = row['Q']
            tgt = row['A']

            # 한글 전처리
            src = self.clean_text(src)
            tgt = self.clean_text(tgt)

            if len(src.split()) > min_length and len(tgt.split()) > min_length:
                # 최소 길이를 넘어가는 문장의 단어만 추가
                wordvocab.add_sentence(src)
                wordvocab.add_sentence(tgt)
                src_clean.append(src)
                tgt_clean.append(tgt)

        self.srcs = src_clean
        self.tgts = tgt_clean
        self.wordvocab = wordvocab

    def normalize(self, sentence):
        return self.normalizer.sub('',sentence)

    def clean_text(self, sentence):
        # 한글 정규화
        sentence = self.normalize(sentence)
        # 형태소 처리
        sentence = self.tagger.morphs(sentence)
        sentence = ' '.join(sentence)
        sentence = sentence.lower()
        return sentence

    def texts_to_sequences(self, sentence):
        # 문장 -> 시퀀스로 변환
        return [self.wordvocab.word2index[w] for w in sentence.split()]

    def pad_sequence(self, sentence_tokens):
        # 특별 토큰이 들어갈 공간 확보
        sentence_tokens = sentence_tokens[:(self.max_length-1)]
        token_length = len(sentence_tokens)
        # print(sentence_tokens)
        # 문장의 맨 끝 부분에 <EOS> 토큰 추가
        sentence_tokens.append(self.EOS_TOKEN)

        for i in range(token_length, (self.max_length-1)):
            sentence_tokens.append(self.PAD_TOKEN)
        return sentence_tokens

    def __getitem__(self, idx): # 클래스의 인덱스에 접근할 때 자동으로 호출되는 메서드
        inputs = self.srcs[idx] # clean_text된 문장
        inputs_sequences = self.texts_to_sequences(inputs)
        inputs_padded = self.pad_sequence(inputs_sequences)

        outputs = self.tgts[idx]
        outputs_sequences = self.texts_to_sequences(outputs)
        outputs_padded = self.pad_sequence(outputs_sequences)

        return torch.tensor(inputs_padded), torch.tensor(outputs_padded)

    def __len__(self):
        return len(self.srcs)

In [ ]:
# 한 문장의 최대 단어 길이를 25로 설정
MAX_LENGTH = 25
dataset = TextDataset('ChatbotData.csv', min_length=3, max_length=MAX_LENGTH)

In [ ]:
# 10번째 데이터 임의 추출
x, y = dataset[10]  # x: torch.tensor(inputs_padded), y: torch.tensor(outputs_padded)

In [ ]:
print(f'x shape: {x.shape}')
print(x)

x shape: torch.Size([25])
tensor([83, 84, 51, 85, 86, 18,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0])


In [ ]:
print(f'y shape: {y.shape}')
print(y)

y shape: torch.Size([25])
tensor([87, 88, 58, 89, 63, 90, 11,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0])


- 문장의 맨 끝에는 2번 토큰(EOS 토큰)이 위치함
- EOS 토큰부터 max_length까지는 PAD 토큰(0)으로 채워짐
- x,y데이터 모두 max_length=25의 크기를 가짐

##### **train/test 데이터 셋 분할**

In [ ]:
len(dataset)

10218

In [ ]:
# 80%의 데이터를 train에 할당
train_size = int(len(dataset) * 0.8)
train_size

8174

In [ ]:
# 나머지 20%의 데이터를 test에 할당
test_size = len(dataset) - train_size
test_size

2044

In [ ]:
from torch.utils.data import random_split

# 랜덤 스플릿으로 분할을 완료합니다
train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

##### **DataLoader 생성**
- 배치구성을 쉽게 하기 위해 `torch.utils.data.DataLoader`를 활용
- train/test 데이터셋 모두 batch_size=16으로 설정

In [ ]:
from torch.utils.data import DataLoader, SubsetRandomSampler

train_loader = DataLoader(train_dataset,
                          batch_size=16,    # 16개의 시퀀스를 한번에 처리
                          shuffle=True)
test_loader = DataLoader(test_dataset,
                         batch_size=16,
                         shuffle=True)

- next와 iter 라는 함수를 사용하면 데이터셋 내부의 데이터를 하나하나씩 뽑을 수 있다.   
(next는 파이썬의 iterator object에서 다음 아이템을 뽑는 함수고 iter는 어떤 오브젝트를 iterator로 바꿔주는 함수이다.)

In [ ]:
# 1개의 배치 데이터를 추출
x, y = next(iter(train_loader))

In [ ]:
# shape: (batch_size, sequence_length)
x.shape, y.shape

(torch.Size([16, 25]), torch.Size([16, 25]))

#### **모델**

##### **Encoder**

In [ ]:
class Encoder(nn.Module):
    def __init__(self, num_vocabs, hidden_size, embedding_dim, num_layers):
        super(Encoder, self).__init__()

        # 단어 사전의 개수 지정
        self.num_vocabs = num_vocabs
        # 임베딩 레이어 정의(number of vocabs, embedding dimension)
        self.embedding = nn.Embedding(num_vocabs, embedding_dim)
        # GRU(embedding dimension)
        self.gru = nn.GRU(embedding_dim,
                          hidden_size,
                          num_layers=num_layers,
                          bidirectional=False)

    def forward(self, x):
        x = self.embedding(x).permute(1, 0, 2)
        output, hidden = self.gru(x)
        return output, hidden

###### **Embedding Layer의 입출력 shape에 대한 이해**
- nn.Embedding: Input Tensor 를 다차원으로 확장시켜주는 기능

In [ ]:
embedding_dim = 64  # 임베딩 차원
embedding = nn.Embedding(dataset.wordvocab.n_words, embedding_dim)  # 인자: (num_embeddigns, embedding_dim)
embedded = embedding(x) # (sequence_length에 대해서 embedding_dim=64를 추가)

print(x.shape)  # (batch_size, sequence_length)
print(embedded.shape)   # (batch_size, sequence_length, embedding_dim)  <- 각 단어별로 embedding_dim 추가
print(embedded)

torch.Size([16, 25])
torch.Size([16, 25, 64])
tensor([[[ 0.1499, -0.6573,  1.5865,  ..., -0.7009,  0.3178, -0.1365],
         [-0.2487, -1.3274, -0.4680,  ..., -0.8904,  0.7825, -1.2692],
         [-0.4853,  0.0265,  0.5685,  ..., -0.4328,  0.6887,  1.8739],
         ...,
         [-1.0751, -0.3323, -0.4610,  ...,  0.5498, -1.0972,  0.2755],
         [-1.0751, -0.3323, -0.4610,  ...,  0.5498, -1.0972,  0.2755],
         [-1.0751, -0.3323, -0.4610,  ...,  0.5498, -1.0972,  0.2755]],

        [[-0.1872, -0.4552,  0.1901,  ...,  0.7542, -1.0157,  0.5308],
         [-1.5540, -0.7176,  1.1023,  ..., -0.8208, -0.3947,  0.9904],
         [ 0.0239,  2.1469, -0.7227,  ..., -0.0692, -0.8305, -2.2648],
         ...,
         [-1.0751, -0.3323, -0.4610,  ...,  0.5498, -1.0972,  0.2755],
         [-1.0751, -0.3323, -0.4610,  ...,  0.5498, -1.0972,  0.2755],
         [-1.0751, -0.3323, -0.4610,  ...,  0.5498, -1.0972,  0.2755]],

        [[ 0.7347, -1.1069,  0.0104,  ..., -0.0928,  0.0638,  0.3041],

In [ ]:
embedded = embedded.permute(1, 0, 2)    # (1번째 차원, 0번째 차원, 2번째 차원)이 되게 변경해라
# (batch_size, sequence_length, , embedding_dim)
# -> (sequence_length, batch_size, embedding_dim)

print(embedded.shape)   # (sequence_length, batch_size, embedding_dim)

torch.Size([25, 16, 64])


> - embedding layer를 통과한 출력을   
`(batch_size, sequence_length, embedding_dim)`   
=> `(sequence_length, batch_size, embedding_dim)` shape 변환을 위해 `permute(1,0,2)`를 수행함
- shape을 변환하는 이유는 GRU 레이어의 입력이 `(sequence_length, batch_size, embedding_dim)`을 수용하기 때문

###### **GRU Layer의 입출력 shape에 대한이해**

https://docs.pytorch.org/docs/stable/generated/torch.nn.GRU.html

- `bidirectional`: true라면 양방향 GRU가 됨
- `num_layers`: Number of recurrent layers
- `o`: sequence의 모든 time step 별 hidden state를 모아놓은 텐서
    -  아래 코드에 한해서는 **64차원의 단어 임베딩 벡터(입력)**를 받아,   
    이전까지의 정보를 압축한 **문맥을 포함한 32차원의 은닉 상태 벡터(출력)**들로 만들어서 time step마다 모아둔 것
- `h` : sequence의 가장 마지막 time step의 hidden state -> Context Vector
    - 즉, `h`는 각 배치마다 마지막 hidden state를 모아놓은 텐서

In [ ]:
hidden_size = 32

gru = nn.GRU(embedding_dim,  # embedding 차원
             hidden_size,   # 문맥을 요약해서 만들 새로운 정보의 차원
             num_layers=1,
             bidirectional=False)

# input(embedded): (sequence_length, batch_size, embedding_dim) = (25, 16, 64)
# h0 : (bidirectional(1) * number of layers(1), batch_size, hidden_size) = (1, 16, 32)
o, h = gru(embedded, None)  # 인자: (input, initial hidden state)

# output(o): (sequence_length, batch_size, hidden_size * bidirectional(1))  = (25, 16, 32*1)
# h: (bidirectional * num_layers, batch_size, hidden_size)  = (1, 16, 32)
print(o.shape)
print(h.shape)

# output의 마지막 hidden state가 h랑 동일한것 확인 가능
(o[-1] == h)

torch.Size([25, 16, 32])
torch.Size([1, 16, 32])


tensor([[[True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True

###### **Encoder의 입출력 shape에 대한 이해**

In [ ]:
NUM_VOCABS = dataset.wordvocab.n_words
print(f'number of vocabs: {NUM_VOCABS}')

number of vocabs: 6435


In [ ]:
# Encoder 정의
encoder = Encoder(NUM_VOCABS, hidden_size=32, embedding_dim=64, num_layers=1)

In [ ]:
# Encoder에 x 통과후 output, hidden_size의 shape 확인
# input(x): (batch_size, sequence_length)
o, h = encoder(x)

print(o.shape)  # (sequence_length, batch_size, hidden_size * bidirectional(1))
print(h.shape)  # (bidirectional(1) * num_layers(1), batch_size, hidden_size)

torch.Size([25, 16, 32])
torch.Size([1, 16, 32])


##### **Decoder**

In [ ]:
class Decoder(nn.Module):
    def __init__(self, num_vocabs, hidden_size, embedding_dim, num_layers=1, dropout=0.2):
        super(Decoder, self).__init__() # 자식클래스(Decoder)가 상속받는 부모클래스(nn.Module)를 자식 클래스(Decoder)에 불러오겠다.
        # 단어사전 개수
        self.num_vocabs=num_vocabs
        self.embedding = nn.Embedding(num_vocabs, embedding_dim)
        self.dropout = nn.Dropout(dropout)
        self.gru = nn.GRU(embedding_dim,
                            hidden_size,
                            num_layers=num_layers,
                            bidirectional=False)
        # 최종 출력은 단어사전의 개수
        self.fc = nn.Linear(hidden_size, num_vocabs)

    def forward(self, x, hidden_state):
        x = x.unsqueeze(0)  # (1, batch_size)로 변환 <- 한번에 한 단어씩 순차적으로 다음 단어를 예측하기 때문에 seq_len = 1
        embedded = F.relu(self.embedding(x))
        embedded = self.dropout(embedded)
        output, hidden = self.gru(embedded, hidden_state)
        # print(output.shape)
        # print(hidden.shape)
        # print(output.squeeze(0).shape)
        output = self.fc(output.squeeze(0)) # (sequence_length, batch_size, hidden_size(32) x bidirectional(1)
        # print(output.shape)
        return output, hidden

- `.squeeze(0)` : 0번째 차원이 1일 경우 제거
    - hidden_state는 squeeze(0) 안해줌

###### **Embedding Layer의 입출력 shape에 대한 이해**

In [ ]:
x = torch.abs(torch.randn(size=(1,16)).long())
print(x)
print(x.shape)
# batch_size = 16이라 가정했을 때,
# x: (1, batch_size)
# 여기서 batch_size => (1, batch_size)로 shape 변환을 선행

tensor([[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0]])
torch.Size([1, 16])


In [ ]:
embedding_dim = 64
embedding = nn.Embedding(dataset.wordvocab.n_words, embedding_dim)

embedded = embedding(x)
print(x.shape)  # (1, 16)
# embedding 출력
print(embedded.shape)   # (1, batch_size, embedding_dim)

torch.Size([1, 16])
torch.Size([1, 16, 64])


###### **GRU Layer의 입/출력 shape에 대한 이해**

In [ ]:
hidden_size = 32

gru =nn.GRU(embedding_dim,
            hidden_size,
            num_layers=1,
            bidirectional=False,
            batch_first=False   # batch_first=False로 지정 => batch 차원이 0차원이 아님
            )

o, h = gru(embedded)
print(o.shape)  # (sequence_length, batch_size, hidden_size * bidirectional(1)) = (1, 16, 32)
print(h.shape)  # (bidirectional(1) * number of recurrent layers(1), batch_size, hidden_size) = (1, 16 , 32)

torch.Size([1, 16, 32])
torch.Size([1, 16, 32])


###### **최종 출력층(FC) shape에 대한 이해**

In [ ]:
fc = nn.Linear(32, NUM_VOCABS)  # 출력은 단어 사전의 개수로 가정
output = fc(o[0])   # (, 32) -> (,NUM_VOCABS)

print(o[0].shape)   # input: (batch_size, output from GRU)
print(output.shape) # output: (batch_size, output_dim)

torch.Size([16, 32])
torch.Size([16, 6435])


##### **Encoder -> Decoder 입출력 shape**

- Decoder에 입력된 Encoder의 `output`, `hidden_state`의 shape을 확인


In [ ]:
decoder = Decoder(num_vocabs=dataset.wordvocab.n_words,
                  hidden_size=32,
                  embedding_dim=64,
                  num_layers=1)

- `hidden_state`만 디코더의 입력으로 활용함
- `x`는 SOS 토큰이 첫번째 입력으로 들어감

In [ ]:
x, y = next(iter(train_loader))
o, h = encoder(x)
print(o.shape, h.shape)
# output: (sequence_length, batch_size, hidden_size(32)*bidirectional(1))
# hidden_state: (bidirectional(1)*number of layers(1), batch_size, hidden_size(32))

torch.Size([25, 16, 32]) torch.Size([1, 16, 32])


- encoder로부터 생성된 hidden_state(`h`)와 SOS 토큰을 Decoder의 입력으로 넣어줌

In [ ]:
x = torch.abs(torch.full(size=(16,), fill_value=SOS_TOKEN).long())
print(x)
x.shape
# batch_size=16이라 가정(16개의 SOS 토큰)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


torch.Size([16])

In [ ]:
decoder_output, decoder_hidden = decoder(x, h)
decoder_output.shape, decoder_hidden.shape
# (batch_size, num_vocabs), (1, batch_size, hidden_size)

(torch.Size([16, 6435]), torch.Size([1, 16, 32]))

- `decoder_output`: (batch_size, num_vocabs) shape으로 출력
- `decoder_hidden`: 입력으로 넣어준 shape과 동일

##### **Seq2Seq**

- 인코더: "입력 문장이 무엇인지 처음부터 알고 있음." 따라서 전체 문장을 미리 받고 내부적으로 순차 처리하여 **하나의 요약본(Context Vector)**을 만드는 것이 목표. -> `input: (batch_size, seq_len=전체문장길이)`

- 디코더: "출력 문장이 무엇이 될지 전혀 모르는 상태에서 만들어가야함." 따라서 한 단어를 예측하고, 그 예측된 단어를 다음 입력으로 사용하는 과정을 반복해야함. 이 때문에 외부에서 **한 단어**씩 입력을 넣어주는 구조가 됨. `input: (batch_size, seq_len=1=한단어)`


- 결론적으로, "인코더도 내부적으로는 한 단어씩 처리하는 것이 맞다." 하지만 모델의 전체 구조상 '문장 전체를 한 번에 입력받아 요약하는 역할'을 하므로 입력 shape을 `(batch_size, seq_len)`로 표현

In [ ]:
class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder, device):
        super(Seq2Seq, self).__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.device = device

    def forward(self, inputs, outputs, teacher_forcing_ratio=0.5):
        # inputs: (batch_size, sequence_length)
        # outputs: (batch_size, sequence_length)
        batch_size, output_length = outputs.shape   # batch_size = batch_size, output_length = sequence_length
        output_num_vocabs = self.decoder.num_vocabs

        # 리턴할 예측된 outputs를 저장할 임시 변수
        # predicted_outputs: (sequence_length, batch_size, num_vocabs) <- 문장의 모든 단어에 대한 예측을 저장할 수 있음
        predicted_outputs = torch.zeros(output_length, batch_size, output_num_vocabs).to(self.device)

        # 인코더에 입력 데이터 주입, encoder_output은 버리고 hidden state만 살림
        # 여기서 hidden_state가 디코더에 주입할 context vector
        # decoder_hidden: (Bidirectional(1) x number of layers(1), batch_size, hidden_size)
        _, decoder_hidden = self.encoder(inputs)

        # (batch_size) shape의 SOS TOKEN으로 채워진 디코더 입력 생성
        decoder_input = torch.full((batch_size, ), SOS_TOKEN, device=self.device)

        # 순회하면서 출력 단어 생성
        # 0번째는 SOS TOKEN이 위치하므로, 1번째 인덱스부터 순회
        for t in range(0, output_length):
            # decoder_input: 디코더 입력 (batch_size) 형태의 SOS TOKEN으로 채워진 입력
            # decoder_output: (batch_size, num_vocabs) <- num_vocabs차원에는 다음으로 이 단어가 예측될것이다!라는 score값이 저장
            # decoder_hidden: (Bidirectional(1) x number of layers(1), batch_size, hidden_size) = context vector와 동일 shape
            decoder_output, decoder_hidden = self.decoder(decoder_input, decoder_hidden)

            # t번째 단어에 디코더의 output 저장
            predicted_outputs[t] = decoder_output

            # teacher forcing 적용 여부 확률로 결정
            # teacher forcing이란: 정답지를 다음 RNN Cell의 입력으로 넣어주는 경우 수렴속도가 빠를 수 있으나, 불안정할 수 있음
            teacher_force = random.random() < teacher_forcing_ratio

            # top1 단어 토큰 예측
            top1 = decoder_output.argmax(1) # num_vocabs차원상 가장 큰값

            # teacher forcing인 경우 ground truth값을, 그렇지 않은 경우, 예측값을 다음 input으로 지정
            decoder_input = outputs[:,t] if teacher_force else top1

        return predicted_outputs.permute(1, 0, 2)   # (batch_size, sequence_length, num_vocabs)로 변경



###### **seq2seq 입출력 확인**

In [ ]:
# encoder 정의
encoder = Encoder(num_vocabs=dataset.wordvocab.n_words,
                  hidden_size=32,
                  embedding_dim=64,
                  num_layers=1)

# decoder 정의
decoder = Decoder(num_vocabs=dataset.wordvocab.n_words,
                  hidden_size=32,
                  embedding_dim=64,
                  num_layers=1)

# seq2seq 정의
seq2seq = Seq2Seq(encoder, decoder, 'cpu')

In [ ]:
x, y = next(iter(train_loader))
print(x.shape, y.shape)
# (batch_size, sequence_length), (batch_size, sequence_length)

torch.Size([16, 25]) torch.Size([16, 25])


In [ ]:
output = seq2seq(x, y)
print(output.shape) # (batch_size, sequence_length, num_vocabs)

torch.Size([16, 25, 6435])


#### **Training**

In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else 'cpu')

NUM_VOCABS = dataset.wordvocab.n_words
HIDDEN_SIZE = 512   # 원활한 결과를 위해 위의 예시에서 하이퍼파라미터 조정됨
EMBEDDING_DIM = 256

print(f"num_vocabs: {NUM_VOCABS}\n============================")

# Encoder 정의
encoder = Encoder(num_vocabs=NUM_VOCABS,
                  hidden_size=HIDDEN_SIZE,
                  embedding_dim=EMBEDDING_DIM,
                  num_layers=1)

# decoder 정의
decoder = Decoder(num_vocabs=NUM_VOCABS,
                  hidden_size=HIDDEN_SIZE,
                  embedding_dim=EMBEDDING_DIM,
                  num_layers=1)

# Seq2Seq 생성
# encoder, decoder를 device 모두 지정
model = Seq2Seq(encoder.to(device), decoder.to(device), device)
print(model)

num_vocabs: 6435
Seq2Seq(
  (encoder): Encoder(
    (embedding): Embedding(6435, 256)
    (gru): GRU(256, 512)
  )
  (decoder): Decoder(
    (embedding): Embedding(6435, 256)
    (dropout): Dropout(p=0.2, inplace=False)
    (gru): GRU(256, 512)
    (fc): Linear(in_features=512, out_features=6435, bias=True)
  )
)


##### **HyperParameter 정의**

In [ ]:
class EarlyStopping:
    def __init__(self, patience=3, delta=0.0, mode='min', verbose=True):
        """
        patience (int): loss or score가 개선된 후 기다리는 기간. default: 3 / 성능이 나아지지 않더라도 3번의 epoch까지는 더 기다려봄
        delta  (float): 개선시 인정되는 최소 변화 수치. default: 0.0    /   미미한 성능향상을 무시하고 싶을 때 설정 가능
        mode     (str): 개선시 최소/최대값 기준 선정('min' or 'max'). default: 'min'.   / loss: 값이 낮을 수록 좋음 -> min 사용 , accuracy: 값이 높을 수록 좋음 ->  max 사용
        verbose (bool): 메시지 출력여부 결정. default: True
        """
        self.early_stop = False
        self.patience = patience
        self.verbose = verbose
        self.counter = 0

        self.best_score = np.inf if mode == 'min' else 0
        self.mode = mode
        self.delta = delta

    # __call__: 클래스의 인스턴스를 함수처럼 호출 가능하게 만들어줌
    def __call__(self, score):
        if self.best_score is None: # best_score가 없다면
            self.best_score = score
            self.counter = 0
        elif self.mode == 'min':    # best_score가 존재하고, mode==min
            if score < (self.best_score - self.delta):  # 성능향상이 이루어졌다면
                self.counter = 0
                self.best_score = score
                if self.verbose:
                    print(f'[EarlyStopping] (Update) Best Score: {self.best_score:.5f}')
            else:   # 성능향상이 이루어지지 않았다면
                self.counter += 1
                if self.verbose:
                    print(f'[EarlyStopping] (Patience) {self.counter}/{self.patience}, ' \
                          f'Best: {self.best_score:.5f}' \
                          f', Current: {score:.5f}, Delta: {np.abs(self.best_score - score):.5f}')

        elif self.mode == 'max':    # best_score가 존재하고, mode!=min, mode=max
            if score > (self.best_score + self.delta):  # 성능향상이 이루어졌다면
                self.counter = 0
                self.best_score = score
                if self.verbose:
                    print(f'[EarlyStopping] (Update) Best Score: {self.best_score:.5f}')
            else:   # 성능향상이 이루어지지 않았다면
                self.counter += 1
                if self.verbose:
                    print(f'[EarlyStopping] (Patience) {self.counter}/{self.patience}, ' \
                          f'Best: {self.best_score:.5f}' \
                          f', Current: {score:.5f}, Delta: {np.abs(self.best_score - score):.5f}')


        if self.counter >= self.patience:   # patience만큼의 epoch을 기다렸는데도 성능향상이 이루어지지 않았다면
            if self.verbose:
                print(f'[EarlyStop Triggered] Best Score: {self.best_score:.5f}')   # 최종 스코어 출력
            # Early Stop
            self.early_stop = True
        else:
            # Continue
            self.early_stop = False

- 훈련에 적용할 하이퍼파라미터 설정

In [ ]:
LR = 1e-3
optimizer = optim.Adam(model.parameters(), lr=LR)
loss_fn = nn.CrossEntropyLoss() # softmax함수가 포함되어져있음

es = EarlyStopping(patience=5,
                   delta=0.001,
                   mode='min',
                   verbose=True
                  )
# ReduceLROnPlateau: 검증 손실(validation loss)이 더 이상 개선되지 않을 때 학습률을 동적으로 감소시켜 모델의 학습을 돕는 기법
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, # 옵티마이저객체
                                                 mode='min',    # 성능 개선 측정 방법
                                                 factor=0.5,    # learning_rate를 감소시킬 비율; 현재 lr에 * 0.5
                                                 patience=2,    # 더이상 성능 개선 안되어도 2번의 연속적인 epoch동안 기다림
                                                 threshold_mode='abs',  # 절대적인 변화량으로 threshold를 해석함
                                                                        # threshold: learning rate를 감소시킬 기준
                                                 min_lr=1e-8,   # learning rate를 감소시킬 최솟값. learning_rate는 이 값보다 작아지지 않음
                                                 verbose=True)

/usr/local/lib/python3.11/dist-packages/torch/optim/lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


##### **trian 함수 정의**

In [ ]:
def train(model, data_loader, optimizer, loss_fn, device):
    model.train()   # 학습모드로 설정
    running_loss=0

    for x, y in data_loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()

        # output: (batch_size, sequence_length, num_vocabs)
        output = model(x, y)
        output_dim = output.size(2) # output_dim: num_vocabs

        # 1번 index부터 슬라이싱한 이유는 0번 index가 SOS TOKEN이기 때문
        # (batch_size * sequnce_length, num_vocabs)로 변경
        output = output.reshape(-1, output_dim) # 배치 내 모든 문장에 있는 **단어 위치별** 예측 결과

        # y:(batch_size, sequence_length) -> (batch_size * sequence_length)로 변경
        y = y.view(-1)  # 간단하게, 밖을 둘러싸고 있던 `[]`하나가 사라짐

        # loss 계산
        # CrossEntropyLos의 input은 (N,C)이라는 2차원을 수용함
        # N: 배치 내에 포함된 모든 개별 토큰(단어)의 총 개수, C: number of classes
        loss = loss_fn(output,y)    # (1,) shape을 갖는 텐서 -> loss.item()으로 가지고 와야함
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * x.size(0)# loss는 보통 한 배치에 대한 평균을 계산 -> 배치 내 모든 문장에 대한 총 손실로 변경

    return running_loss / len(data_loader)  # 배치 개수로 loss를 평균내서 리턴

In [ ]:
import numpy as np

t = np.random.randn(2, 4, 3)
print(t.shape)
print(t)
print('-'*50)
print(t.reshape(-1, 3).shape)
print(t.reshape(-1, 3))


(2, 4, 3)
[[[ 0.72370057 -1.59634392 -0.19806267]
  [-0.71904181  0.29846875 -0.93228796]
  [ 2.27514803 -1.54657777  0.8648444 ]
  [ 0.11272371  0.20671143  1.72048111]]

 [[-1.01671768  0.40326562 -0.74633451]
  [-0.5216068   1.16752092 -0.47201208]
  [ 1.3336449   1.64377082  1.59777122]
  [-0.19518903  0.59222514  0.05467594]]]
--------------------------------------------------
(8, 3)
[[ 0.72370057 -1.59634392 -0.19806267]
 [-0.71904181  0.29846875 -0.93228796]
 [ 2.27514803 -1.54657777  0.8648444 ]
 [ 0.11272371  0.20671143  1.72048111]
 [-1.01671768  0.40326562 -0.74633451]
 [-0.5216068   1.16752092 -0.47201208]
 [ 1.3336449   1.64377082  1.59777122]
 [-0.19518903  0.59222514  0.05467594]]


##### **evaluation 함수 정의**

In [ ]:
def evaluate(model, data_loader, loss_fn, device):
    model.eval()    # 모델 평가시 사용. Dropout, Batchnorm등의 기능들을 비활성화해준다고 한다.
                    # 모델링 시 training과 inference시에 다르게 동작하는 layer들이 존재하기 때문에 사용

    eval_loss = 0

    with torch.no_grad():   # autograd를 끔으로써 메모리 사용량을 줄이고 연산 속도를 높히기 위함
        for x, y in data_loader:
            x, y = x.to(device), y.to(device)
            output = model(x, y)
            output_dim = output.size(2)
            output = output.reshape(-1, output_dim)
            y = y.view(-1)

            # Loss 계산
            loss = loss_fn(output, y)

            eval_loss += loss.item() * x.size(0)

    return eval_loss / len(data_loader)

##### **랜덤 샘플링 후 결과 추론**

- sequence를 다시 문장으로 바꾸어 문장 형식으로 출력하기 위한 함수

In [ ]:
def sequence_to_sentence(sequences, index2word):
    outputs = []
    for p in sequences: # 시퀀스에 있는 정수 인덱스를 한개씩 가져옴

        word = index2word[p]
        if p not in [SOS_TOKEN, EOS_TOKEN, PAD_TOKEN]:  #  토큰에 안들어가면
            outputs.append(word)
        if word == EOS_TOKEN:   # EOS TOKEN을 만나면
            break
    return ' '.join(outputs)

In [ ]:
def random_evaluation(model, dataset, index2word, device, n=10):

    n_samples = len(dataset)    # data sample의 개수
    indices = list(range(n_samples))    # [0~n_samples-1]를 포함한 인덱스 생성
    np.random.shuffle(indices)      # Shuffle
    sampled_indices = indices[:n]   # Sampling N indices

    # 샘플링한 데이터를 기반으로 DataLoader 생성
    sampler = SubsetRandomSampler(sampled_indices)  # SubsetRandomSampler: 주어진 인덱스목록에서 요소를 무작위로샘플링함
    sampled_dataloader = DataLoader(dataset, batch_size=10, sampler=sampler)

    model.eval()
    with torch.no_grad():
        for x, y in sampled_dataloader:
            x, y = x.to(device), y.to(device)
            output = model(x, y, teacher_forcing_ratio=0)   # 평가시에는 teacher forcing 안씀
            # output: (number of samples, sequence_length, num_vocabs)

            # PyTorch 텐서를 NumPy 배열로 변환하여 학습 외의 다른 목적으로 사용할 수 있도록 하기 위해서 사용(아래의 반복문)
            preds = output.detach().cpu().numpy()   # GPU에 올라가 있는 tensor를 이용하려면 numpy 또는 list로 변환해야함
            x = x.detach().cpu().numpy()    # GPU에 올라가 있는 tensor를 이용하려면 numpy 또는 list로 변환
            y = y.detach().cpu().numpy()    # GPU에 올라가 있는 tensor를 이용하려면 numpy 또는 list로 변환

            for i in range(n):
                print(f'질문   : {sequence_to_sentence(x[i], index2word)}')
                print(f'답변   : {sequence_to_sentence(y[i], index2word)}')
                print(f'예측답변: {sequence_to_sentence(preds[i].argmax(1), index2word)}')
                print('==='*10)

- detach(): 연산 기록에서 역전파를 중단하고 분리한 텐서 반환
- cpu(): GPU 메모리에 올라가있는 tensor를 CPU메모리로 복사
- numpy(): CPU 메모리에 올려져 있는 tensor만 해당 함수를 적용가능. tensor를 numpy로 변환해줌

In [ ]:
idx = list(range(10))
idx

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.random.shuffle(idx)
idx

[9, 0, 4, 6, 3, 5, 7, 1, 2, 8]

##### **훈련 시작**

In [ ]:
!mkdir models

- 모델저장하기: https://tutorials.pytorch.kr/beginner/saving_loading_models.html

In [ ]:
NUM_EPOCHS = 20
STATEDICT_PATH = 'models/seq2seq-chatbot-kor.pt'

best_loss = np.inf

for epoch in range(NUM_EPOCHS):
    loss = train(model, train_loader, optimizer, loss_fn, device)

    val_loss = evaluate(model, test_loader, loss_fn, device)

    if val_loss < best_loss:
        best_loss = val_loss
        torch.save(model.state_dict(), STATEDICT_PATH)

    if epoch % 5 == 0:  # 5번째 epoch마다
        print(f'epoch: {epoch+1}, loss: {loss:.4f}, val_loss: {val_loss:.4f}')

    # Early Stop
    es(loss)
    if es.early_stop:
        break

    # Scheduler
    scheduler.step(val_loss)

# .load_state_dict(): torch.load()로 불러온 딕셔너리를 실제 모델 객체에 적용하는 역할
model.load_state_dict(torch.load(STATEDICT_PATH))   # load_state_dict() 함수에는 저장된 객체의 경로가 아닌, 사전 객체를 전달
                                                    # torch.load(PATH): 파이썬 딕셔너리 객체로 되돌려둠
                                                    # 모델.load_state_dict(): 모델에 불러온 딕셔너리 적용
torch.save(model.state_dict(), f'models/seq2seq-chatbot-kor-{best_loss:.4f}.pt')

epoch: 1, loss: 32.6597, val_loss: 29.2692
[EarlyStopping] (Update) Best Score: 32.65969
[EarlyStopping] (Update) Best Score: 28.12655
[EarlyStopping] (Update) Best Score: 26.08314
[EarlyStopping] (Update) Best Score: 23.97805
[EarlyStopping] (Update) Best Score: 21.29754
epoch: 6, loss: 18.4086, val_loss: 26.8496
[EarlyStopping] (Update) Best Score: 18.40861
[EarlyStopping] (Update) Best Score: 15.51410
[EarlyStopping] (Update) Best Score: 12.86352
[EarlyStopping] (Update) Best Score: 9.37432
[EarlyStopping] (Update) Best Score: 7.46079
epoch: 11, loss: 6.2363, val_loss: 29.9187
[EarlyStopping] (Update) Best Score: 6.23629
[EarlyStopping] (Update) Best Score: 4.75839
[EarlyStopping] (Update) Best Score: 4.07226
[EarlyStopping] (Update) Best Score: 3.53820
[EarlyStopping] (Update) Best Score: 2.85709
epoch: 16, loss: 2.5622, val_loss: 33.0285
[EarlyStopping] (Update) Best Score: 2.56222
[EarlyStopping] (Update) Best Score: 2.37652
[EarlyStopping] (Update) Best Score: 2.09646
[EarlyStop

#### 결과

In [ ]:
model.load_state_dict(torch.load(STATEDICT_PATH))
random_evaluation(model, test_dataset, dataset.wordvocab.index2word, device)

질문   : 추억 에 머물 다 .
답변   : 때로 는 추억 이 힘 이 되 기 도 하 죠 .
예측답변: 생각 이 웬수 나 봐요 .
질문   : 좋 아 하 는 애 가 좀 노 는 애 인데 좋 아 해도 돼 ?
답변   : 어떤 사람 이 냐 에 따라 다릅니다 .
예측답변: 좋 하 는 게 좋 을 것 같 아요 .
질문   : 베란다 도 꾸미 니까 예쁘 더라 .
답변   : 심플 하 게 꾸며 보 세요 .
예측답변: 이제 한 순간 이 있 .
질문   : 대리 님 이 너무 갈궈
답변   : 더 웃 으면서 대해 보 세요 .
예측답변: 더 한 아이스크림 좋 을 거 예요 .
질문   : 오늘 화장 이 안 먹 어
답변   : 각질 제거 를 해 보 세요 .
예측답변: 건강 한 과일 먹 고 맛있 세요 .
질문   : 생리통 때문 에 배 아파
답변   : 힘들 겠 어요 .
예측답변: 잘 하 지 마세요 .
질문   : 오늘 은 결재 가 나야 할텐데
답변   : 그럴 수 있 을 거 예요 .
예측답변: 잘 할 수 있 을 거 예요 .
질문   : 과함 설렘 후 에 지금 은 안 설레
답변   : 초반 에 너무 설렜 나 봐요 .
예측답변: 은연 중 에 는 생각 이 에요 .
질문   : 약 챙겨 먹 어야지
답변   : 꼬박꼬박 챙겨 드세요 .
예측답변: 건강 한 과일 드세요 .
질문   : 이 사람 은 사랑 이 참 쉬운가 봐 내 가 우습 나 ?
답변   : 참 을 수 없 는 가벼움 이 네요 .
예측답변: 사랑 은 는 이 없 는 것 도 중요 해요 .
